<a href="https://colab.research.google.com/github/Ayikanying-ux/Getting_started_-with_deep_learning/blob/main/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x = tf.constant([[1., 2., 3.],
                [4., 5., 6.]])

In [3]:
print(x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [4]:
print(x.shape)

(2, 3)


In [5]:
print(x.dtype)

<dtype: 'float32'>


In [6]:
x+x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [7]:
5*x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [9]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [11]:
tf.concat([x, x, x], axis=0)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [12]:
tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [13]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [16]:
tensor = tf.convert_to_tensor([1, 2, 3])
print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [18]:
print(tf.reduce_sum([1, 2, 3]))

tf.Tensor(6, shape=(), dtype=int32)


In [19]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using GPU")
else:
  print("TensorFlow **IS NOT** using GPU")

TensorFlow **IS NOT** using GPU


### Tensor Variables
- Getting stated with tensorflow variables

#### Introduction to Variables
- A tensorflow variable is the recommended way to represent shared, persistent state you program manipulates.
- This shows how to create, update, and manage instances of tf.Variable in TensorFlow



### Creating a variable
- To create a variable, provide an initial value. the tf.Variable will have the same dtype as the initialization value

In [31]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)
my_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>



---
- Variables can be of any kind of types


In [26]:
bool_variable = tf.Variable([False, False, False, False])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])



---
A variable looks and acts like a tensor, and in fact is a data structure backed by a tf.Tensor. Like tensors, they have a dtype and a shape, and can be exported to Numpy


In [28]:
print("Shape:", my_variable.shape)
print("DType:", my_variable.dtype)
print("As Numpy:", my_variable.numpy())

Shape: (2, 2)
DType: <dtype: 'float32'>
As Numpy: [[1. 2.]
 [3. 4.]]




---
Most tensors operations work on variables as expected, although variables cannot be reshape



In [30]:
print("A variable:", my_variable)
print("\nViewed as a tensor:", tf.convert_to_tensor(my_variable))
print("\nIndex of highest value:", tf.math.argmax(my_variable))

# This creates a new tensor, it does not reshape the variable
print("\nCopying and reshaping:", tf.reshape(my_variable, [1, 4]))

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)

Copying and reshaping: tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)




---
- Variables are backed by tensors, you can assign the tensor using tf.Variable.assign. Calling the assign does not (usually) allocate a new tensor instead the existing tensor's memory is reused


In [32]:
a = tf.Variable([2.0, 3.0])
# This will keep the same dtype, float32
a.assign([1, 2])
# Not allowed as it resizes the variable
try:
  a.assign([1.0, 2.0, 3.0])
except Exception as e:
  print(f"{type(e).__name__}: e{e}")

ValueError: eCannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2,), and the assigned value shape (3,) are incompatible.




---
- If you use a variable like a tensor in operations, you will usually operate on the backing tensor
- Creating new variables from existing variables duplicates the backing tensors. Two variables will not share the same memory


In [33]:
a = tf.Variable([2.0, 3.0])
# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])

# a and b are different
print(a.numpy())
print(b.numpy())

# There are other versions of assign
print(a.assign_add([2, 3]).numpy())
print(a.assign_sub([7, 9]).numpy())

[5. 6.]
[2. 3.]
[7. 9.]
[0. 0.]


### Lifecycles, naming, and watching
- In python-based TensorFlow, tf.Variable instance have the same lifecycle as other python objects. When there are no references to a variable it is automatically deallocated.

- Variables can also be named which can help you track and debug them. You can give two variables the same name

In [34]:
# Create a and b; they will have the same name but will be backed by
# different tensors.
a = tf.Variable(my_tensor, name="Mark")
# A new variable with the same name, but different value
# Note that the scalar add is broadcast
b = tf.Variable(my_tensor + 1, name="Mark")

# These are elementwise-unequal, despite having the same name
print(a == b)


tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)




---
- Variable names are preserved when saving and loading models. By default, variables in models will acquire unique variable names automatically, so you don't need to assign them yourself unless you want to.

- Although variables are important for differentiation, some variables will not need to be differentiated. You can turn off gradients for a variable by setting trainable to false at creation. An example of a variable that would not need gradients is a training step counter.

In [38]:
step_counter = tf.Variable(1, trainable=False)

### Placing variable and tensors
- For better performance, TensorFlow will attempt to place tensors and variables on the fastest device compatible with its dtype. This means most variables are placed on a GPU if one is available.

- However, you can override this. In this snippet, place a float tensor and a variable on the CPU, even if a GPU is available. By turning on device placement logging (see Setup), you can see where the variable is placed.



In [36]:
with tf.device('CPU:0'):

  # Create some tensors
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
  c = tf.matmul(a, b)

print(c)


tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [37]:
with tf.device('CPU:0'):
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.Variable([[1.0, 2.0, 3.0]])

with tf.device('GPU:0'):
  # Element-wise multiply
  k = a * b

print(k)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)
